// <auto-generated />
using System;
using Agence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Agence.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Agence.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");
                });

            modelBuilder.Entity("Agence.Models.Nature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nature");
                });

            modelBuilder.Entity("Agence.Models.Registre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresseClient")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAffectation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatePaiement")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateRemise")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAffaire")
                        .HasColumnType("TEXT")
                        .HasMaxLength(12);

                    b.Property<int>("NOrdre")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NatureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomClient")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT")
                        .HasMaxLength(250);

                    b.Property<bool>("Realise")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("NAffaire")
                        .IsUnique();

                    b.HasIndex("NatureId");

                    b.ToTable("Registres");
                });

            modelBuilder.Entity("Agence.Models.Registre", b =>
                {
                    b.HasOne("Agence.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId");

                    b.HasOne("Agence.Models.Nature", "Nature")
                        .WithMany()
                        .HasForeignKey("NatureId");
                });
#pragma warning restore 612, 618
        }
    }
}
